# Generated by Django 6.0.4 on 2026-05-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_text', models.TextField(verbose_name='Сообщение пользователя')),
                ('bot_response', models.TextField(verbose_name='Ответ бота')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'История сообщений',
                'ordering': ['created_at'],
            },
        ),
    ]
